### ISSUE TITLE
Unable to run the new Appimage gui on opensuse leap 15.1

### ISSUE THREAD

**Issue by wa7qzr** [pocketnetteam/pocketnet.gui#33]
When I attempt to run the appimage from the console, this is what happens:

11:14:30.142 › First check updates...
11:14:30.176 › Checking for update
{ nedbkey: 'settings',
  nedbpath: { settings: './data/settings' },
  nodes:
   { defaults:
      { port: 38081, ws: 8010, rpcuser: 'login', rpcpass: 'password' },
     stable: [ [Object] ] },
  server: true,
  ports: { https: 8888, wss: 8088 },
  ssl:
   { key: './cert/key.pem',
     cert: './cert/cert.pem',
     passphrase: 'password' },
  fbk: './private/pocketnet-firebase.json',
  dbEnable: true,
  db:
   { host: 'localhost',
     port: 5432,
     max: 10,
     idleTimeoutMillis: 30000,
     user: 'postgres',
     database: 'login',
     password: 'password' },
  refkey: '',
  captcha: true,
  iplimiter: true,
  node:
   { Enable: false,
     BinPath: '',
     ConfPath: '',
     DataPath: '',
     SetPrivateKey: false,
     control:
      { state: '-', addresses: '-', lastBlock: '-', running: false } } }
(node:9974) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
11:14:31.723 › Update for version 0.1.2-beta is not available (latest version: 0.1.2-beta, downgrade is disallowed).
Error: Bitcoin JSON-RPC: Connection Rejected: 401 Unnauthorized
    at IncomingMessage.<anonymous> (/tmp/.mount_PocketPi5T36/resources/app.asar/proxy/rpc.js:84:26)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
running: false enable: false
running: false enable: false
pre getnodeinfo undefined
(This just goes on and on, forever, until stopped.)
...
running: false enable: false
pre getnodeinfo undefined
running: false enable: false
running: false enable: false
pre getnodeinfo undefined
running: false enable: false
node signal stop..
Error: Bitcoin JSON-RPC: Request Error: connect ECONNREFUSED 127.0.0.1:36061
    at ClientRequest.<anonymous> (/tmp/.mount_PocketPi5T36/resources/app.asar/proxy/rpc.js:116:19)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
stop 521

Some of the error messages make me think this has to run alongside the node, but, I don't know.
FWIW, the 0.0.55.AppImage client works; not perfectly, but it works.

**Comment by andyoknen** [comment]
Node support in the node is under development - this is normal.
