### ISSUE TITLE
Bastyon.apk Will Not Sideload

### ISSUE THREAD

**Issue by graebeerd** [pocketnetteam/pocketnet.gui#344]
I've got a LG G7 ThinQ, android version 9, yes, I need a newer phone. The .54 apk refuses to sideload but looking in the log, no errors found. It attempts but never finishes with the error in Firefox Nightly that 'something went wrong' and a slightly different error in Google Files 'Something went wrong. The app was not installed.'

I thought it may have been because I had debugging turned on but turned it off and still the same error. The original apk from the app store installed fine back when it was available.

Ok, edited

Downloaded SAI and tried to install from that and found an error:

The App signature does not match the previously install app

It will suck if I can't get this back on my phone so - uninstall the last update and try to install the 1.5.4?

**Comment by graebeerd** [comment]
Deleted the Playstore-installed Bastyon app and tried to install 1.5.4 apk and still errors out initially with the 'DISPLAY_NAME column is null.' and here is the full error:

com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
at com.aefyr.sai.model.apksource.DefaultApkSource.getApkLocalPath(DefaultApkSource.java:47)
at com.aefyr.sai.model.apksource.FilterApkSource.getApkLocalPath(FilterApkSource.java:60)
at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:28)
at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:93)
at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(Unknown Source:6)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

**Comment by graebeerd** [comment]
0.5.8 - SAME PROBLEM - Maybe someone could address this in the next rollup?
